### ISSUE TITLE
compile error w/ kotlinx.coroutines

### ISSUE THREAD

**Issue by kysantt** [eclipse-aspectj/aspectj#183] opened 2022-09-21 02:42 UTC
The error happens at the below code when compiling with kotlinx.coroutines.
The current aspectj compiler can't recognize the last parameter on functional interface such as kotlin.jvm.functions.Function3.
In case of  kotlin.jvm.functions.Function3, tvs.length is 4 and typeParameters.length is 3. So, error happens.
Please see the below detailed logs for more information.

```java
if (tvs.length != typeParameters.length) {
  world.getMessageHandler()
    .handleMessage(
      new Message("Mismatch when building parameterization map. For type '" + this.signature +
                  "' expecting "+tvs.length+":["+toString(tvs)+"] type parameters but found "+typeParameters.length+
                  ":["+toString(typeParameters)+"]", "",
        IMessage.ERROR, getSourceLocation(), null,
        new ISourceLocation[] { getSourceLocation() }));
} else {
  for (int i = 0; i < tvs.length; i++) {
    parameterizationMap.put(tvs[i].getName(), typeParameters[i]);
  }
}
```

error log:

```text
java.lang.Exception
        at org.aspectj.weaver.ResolvedType.getMemberParameterizationMap(ResolvedType.java:996)
        at org.aspectj.weaver.ReferenceType.getDeclaredInterfaces(ReferenceType.java:763)
        at org.aspectj.weaver.ReferenceType.isAssignableFrom(ReferenceType.java:644)
        at org.aspectj.weaver.ReferenceType.isAssignableFrom(ReferenceType.java:650)
        at org.aspectj.weaver.ResolvedType.isTopmostImplementor(ResolvedType.java:2395)
        at org.aspectj.weaver.ResolvedTypeMunger.matches(ResolvedTypeMunger.java:133)
        at org.aspectj.weaver.ConcreteTypeMunger.matches(ConcreteTypeMunger.java:81)
        at org.aspectj.weaver.bcel.BcelWeaver.weaveNormalTypeMungers(BcelWeaver.java:1645)
        at org.aspectj.weaver.bcel.BcelWeaver.addNormalTypeMungers(BcelWeaver.java:1457)
        at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1131)
        at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.weaveQueuedEntries(AjPipeliningCompilerAdapter.java:510)
        at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.queueForWeaving(AjPipeliningCompilerAdapter.java:446)
        at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.afterProcessing(AjPipeliningCompilerAdapter.java:431)
        at org.aspectj.ajdt.internal.compiler.CompilerAdapter.ajc$after$org_aspectj_ajdt_internal_compiler_CompilerAdapter$5$6b855184(CompilerAdapter.aj:104)
        at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.process(Compiler.java:943)
        at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.processCompiledUnits(Compiler.java:576)
        at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:476)
        at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:427)
        at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performCompilation(AjBuildManager.java:1104)
        at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:275)
        at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:188)
        at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:103)
        at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:47)
        at org.aspectj.tools.ajc.Main.run(Main.java:374)
        at org.aspectj.tools.ajc.Main.runMain(Main.java:253)
        at org.aspectj.tools.ajc.Main.main(Main.java:84)
```

**Comment by alsu4r** [comment] 2022-09-21 04:56
For simple code test, you can see the ajc compilation errors with the simple kotlin code below.

`    interface ICallerGen<in T> {
        public suspend fun call(value: T)
    }
    val fun3 = ICallerGen<Any?>::call //--> ajc build error Function3`

**Comment by kriegaex** [comment] 2022-10-08 08:12
I do not speak Kotlin. But I created a simple Maven project, compiled yout sample code and manually applied binary weaving to it (without an aspect, because you did not provide one). I did not experience any problems.

There are so many variables here - Java version, AspectJ version, Kotlin version, AspectJ compiler bytecode target version, aspect(s) used and many more - that I cannot say anything intelligent about your problem. So please, make it reproducible by providing me with a minimal, but complete example project. This is called an [MCVE](https://stackoverflow.com/help/mcve). I cannot analyse invisible code.

**Comment by kriegaex** [comment] 2022-11-05 08:20
I am closing this issue as invalid, because I could not reproduce the problem and there was no reaction to my question. Feel free to react and provide more information, then I can reopen it.

**Closed as completed by kriegaex** 2022-11-05 08:20 UTC
Labels: invalid
