### ISSUE TITLE
Compilation errors for native AspectJ keywords enclosed in parentheses

### ISSUE THREAD

**Issue by kriegaex** [eclipse-aspectj/aspectj#20] opened 2020-09-11 01:41 UTC
I found this at https://stackoverflow.com/q/63804177/1082681.

Trying to compile

```java
package de.scrum_master.app;

public class Application {
  public void runRule(boolean before) {
    String str = (before) ? "before" : "after";
  }
}
```

leads to a compilation error in AJ 1.9.6:

```none
.../Application.java:5 [error] Syntax error, insert "|| Expression" to complete Expression
String str = (before) ? "before" : "after";
```

Removing the redundant braces around `(before)` fixes the problem. The same sample code compiles fine with Javac. I am not sure if this is an Ejc or Ajc problem, I did not double-check.

**Comment by aclement** [comment] 2020-09-11 18:43
Yeah, there are some nuances in how variables named after AspectJ keywords are handled and we don't have the test coverage.  Place to look at the issue is the java.g in here: https://github.com/eclipse/org.aspectj.shadows/blob/aj_19/org.eclipse.jdt.core/grammar/java.g (so not in this project).

It will be incorrect use of the NameOrAj or SimpleNameOrAj entries I think.

**Comment by kriegaex** [comment] 2020-09-12 00:00
Oh right, `before` is a keyword in native AspectJ syntax! _clicking sound in my mind_

This repository must be really old, mentioning difficult 3-way merges with CVS. 😉 Thanks to Git 3-way merges should be much less painful now, at least I hope so for you.

**Comment by kriegaex** [comment] 2022-12-31 08:51
AspectJ's variant of JDT Core has long since been moved to GitHub, i.e. the new location of the _java.g_ grammar file is https://github.com/eclipse/aspectj.eclipse.jdt.core/blob/aspectj/org.eclipse.jdt.core.compiler.batch/grammar/java.g.

**Comment by kriegaex** [comment] 2022-12-31 11:56
> Yeah, there are some nuances in how variables named after AspectJ keywords are handled and we don't have the test coverage. Place to look at the issue is the java.g in (...)
> 
> It will be incorrect use of the NameOrAj or SimpleNameOrAj entries I think.

I do not know how to exactly read that grammar. I tried to trace some clues there, but did not find anything and need your help, @aclement.

What I do know is that this issue is not limited to ternary expressions but to parentesised patterns containing native AspectJ keywords in general, i.e. something like `boolean foo = (before)` where a parenthesised expression should be allowed. Unaffected are cases in which parentheses do not belong to the expression as such, e.g. `switch (before)`. But then again, `switch ((before))` contains a parenthesised expression and triggers a compiler error.

Only with some Java 17 changes, the grammar got a separate `ParenthesizedPattern` symbol, see [this section]( https://github.com/eclipse/aspectj.eclipse.jdt.core/blob/83dca9f647436187c69f839a9eff59c13365c0e3/org.eclipse.jdt.core.compiler.batch/grammar/java.g#L1918-L1926). But that did not introduce the problem. I tried compiling sample code with AJC as old as 1.8.12, and the issue is the same there, i.e. it is an old bug.

There is also this whole long section "Duplicate rules to remove ambiguity for (x)" starting [here](https://github.com/eclipse/aspectj.eclipse.jdt.core/blob/83dca9f647436187c69f839a9eff59c13365c0e3/org.eclipse.jdt.core.compiler.batch/grammar/java.g#L3406-L3408), but also in there I did not find anything out of the ordinary. I am guessing, however, that I am missing something here, which Andy might easily spot.

**Comment by kriegaex** [comment] 2023-01-04 14:12
For the record (CC @aclement): Actually, the problem was in another part of the grammar. I was able to find the right spot by compiling a JDT Core version with `org.eclipse.jdt.internal.compiler.parser.TheOriginalJDTParserClass#DEBUG` set to `true` and compiling a simplified version of the [new regression test](https://github.com/eclipse/org.aspectj/pull/207/files#diff-4f3af45b23825295333f484b3bbf63feeec66bdabb928a47f2e9fddb607f0271) with AJC, inspecting the parser's debug log. A similar approach might help in the future.

**Closed as completed** 2023-01-04 14:19 UTC
Labels: bug, JDT Core

**Comment by aclement** [comment] 2023-01-04 23:43
That's good digging, if possible it'd be worth capturing that debugging approach somewhere more visible in project docs for anyone in future that wants to look at errors in this area.
